services:
  asperguide-frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.front
    image: local_asperguide_frontend
    container_name: local_asperguide_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - asperguide-backend
    networks:
      - db_back
